-- MySQL Script generated by MySQL Workbench
-- Mon May 15 14:09:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Produkt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produkt` (
  `idProdukt` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `brand` VARCHAR(45) NULL,
  `price` DECIMAL(45) NOT NULL,
  `category` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`idProdukt`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pirceji`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pirceji` (
  `idPirceji` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `Produkt_idProdukt` INT NOT NULL,
  PRIMARY KEY (`idPirceji`, `Produkt_idProdukt`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Pirceji_Produkt1_idx` (`Produkt_idProdukt` ASC) VISIBLE,
  CONSTRAINT `fk_Pirceji_Produkt1`
    FOREIGN KEY (`Produkt_idProdukt`)
    REFERENCES `mydb`.`Produkt` (`idProdukt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zakaz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zakaz` (
  `idzakaz` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `Total_cena` DECIMAL(45) NOT NULL,
  `Pirceji_idPirceji` INT NOT NULL,
  `Pirceji_Produkt_idProdukt` INT NOT NULL,
  PRIMARY KEY (`idzakaz`, `Pirceji_idPirceji`, `Pirceji_Produkt_idProdukt`),
  INDEX `fk_zakaz_Pirceji1_idx` (`Pirceji_idPirceji` ASC, `Pirceji_Produkt_idProdukt` ASC) VISIBLE,
  CONSTRAINT `fk_zakaz_Pirceji1`
    FOREIGN KEY (`Pirceji_idPirceji` , `Pirceji_Produkt_idProdukt`)
    REFERENCES `mydb`.`Pirceji` (`idPirceji` , `Produkt_idProdukt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detail` (
  `iddetail` INT NOT NULL AUTO_INCREMENT,
  `zakaz_idzakaz` INT NOT NULL,
  `zakaz_Pirceji_idPirceji` INT NOT NULL,
  `zakaz_Pirceji_Produkt_idProdukt` INT NOT NULL,
  PRIMARY KEY (`iddetail`, `zakaz_idzakaz`, `zakaz_Pirceji_idPirceji`, `zakaz_Pirceji_Produkt_idProdukt`),
  INDEX `fk_detail_zakaz1_idx` (`zakaz_idzakaz` ASC, `zakaz_Pirceji_idPirceji` ASC, `zakaz_Pirceji_Produkt_idProdukt` ASC) VISIBLE,
  CONSTRAINT `fk_detail_zakaz1`
    FOREIGN KEY (`zakaz_idzakaz` , `zakaz_Pirceji_idPirceji` , `zakaz_Pirceji_Produkt_idProdukt`)
    REFERENCES `mydb`.`zakaz` (`idzakaz` , `Pirceji_idPirceji` , `Pirceji_Produkt_idProdukt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admin_zakaz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin_zakaz` (
  `idAdmin_zakaz` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  `detail_iddetail` INT NOT NULL,
  `detail_zakaz_idzakaz` INT NOT NULL,
  `detail_zakaz_Pirceji_idPirceji` INT NOT NULL,
  `detail_zakaz_Pirceji_Produkt_idProdukt` INT NOT NULL,
  PRIMARY KEY (`idAdmin_zakaz`, `detail_iddetail`, `detail_zakaz_idzakaz`, `detail_zakaz_Pirceji_idPirceji`, `detail_zakaz_Pirceji_Produkt_idProdukt`),
  INDEX `fk_Admin_zakaz_detail1_idx` (`detail_iddetail` ASC, `detail_zakaz_idzakaz` ASC, `detail_zakaz_Pirceji_idPirceji` ASC, `detail_zakaz_Pirceji_Produkt_idProdukt` ASC) VISIBLE,
  CONSTRAINT `fk_Admin_zakaz_detail1`
    FOREIGN KEY (`detail_iddetail` , `detail_zakaz_idzakaz` , `detail_zakaz_Pirceji_idPirceji` , `detail_zakaz_Pirceji_Produkt_idProdukt`)
    REFERENCES `mydb`.`detail` (`iddetail` , `zakaz_idzakaz` , `zakaz_Pirceji_idPirceji` , `zakaz_Pirceji_Produkt_idProdukt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `uzsername` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `Admin_zakaz_idAdmin_zakaz` INT NOT NULL,
  PRIMARY KEY (`idAdmin`, `Admin_zakaz_idAdmin_zakaz`),
  INDEX `fk_Admin_Admin_zakaz1_idx` (`Admin_zakaz_idAdmin_zakaz` ASC) VISIBLE,
  CONSTRAINT `fk_Admin_Admin_zakaz1`
    FOREIGN KEY (`Admin_zakaz_idAdmin_zakaz`)
    REFERENCES `mydb`.`Admin_zakaz` (`idAdmin_zakaz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`karzina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`karzina` (
  `idkarzina` INT NOT NULL AUTO_INCREMENT,
  `quantity` VARCHAR(45) NOT NULL,
  `Pirceji_idPirceji` INT NOT NULL,
  `Pirceji_Produkt_idProdukt` INT NOT NULL,
  `Produkt_idProdukt` INT NOT NULL,
  PRIMARY KEY (`idkarzina`, `Pirceji_idPirceji`, `Pirceji_Produkt_idProdukt`, `Produkt_idProdukt`),
  INDEX `fk_karzina_Pirceji1_idx` (`Pirceji_idPirceji` ASC, `Pirceji_Produkt_idProdukt` ASC) VISIBLE,
  INDEX `fk_karzina_Produkt1_idx` (`Produkt_idProdukt` ASC) VISIBLE,
  CONSTRAINT `fk_karzina_Pirceji1`
    FOREIGN KEY (`Pirceji_idPirceji` , `Pirceji_Produkt_idProdukt`)
    REFERENCES `mydb`.`Pirceji` (`idPirceji` , `Produkt_idProdukt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_karzina_Produkt1`
    FOREIGN KEY (`Produkt_idProdukt`)
    REFERENCES `mydb`.`Produkt` (`idProdukt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
